#!/bin/bash

set -uex

install-packages \
    openssh \
    ntpdate \
    bind \
    bind-utils \
    openssh-server \
    git \
    puppet \
    facter \
    tar \
    ntp \

sed --in-place -e s/Type=oneshot/"Type=oneshot\nTimeoutSec=0"/ /lib/systemd/system/cloud-final.service

