#!/bin/bash

set -e

OSE_VERSION=${DIB_OSE_VERSION:="1.2"}

# Download the OSE installer, the default version is 1.2
wget https://raw.github.com/openshift/openshift-extras/enterprise-${OSE_VERSION}/enterprise/install-scripts/generic/openshift.sh

# The openshift-wait4extnet.sh can be executed at runtime if you want to check
# for external connectivity before executing the installer, alternatively you
# can just execute the openshift.sh script.

cat openshift.sh >> openshift-wait4extnet.sh
