- job:
    name: heat-templates-check
    parent: devstack
    run: playbooks/devstack/run.yaml
    timeout: 7500
    required-projects:
      - opendev.org/openstack/heat
      - opendev.org/openstack/heat-agents
      - opendev.org/openstack/heat-templates
    roles:
      - zuul: opendev.org/openstack/devstack
    vars:
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
      devstack_local_conf:
        post-config:
          $HEAT_CONF:
            DEFAULT:
              convergence_engine: true
              logging_exception_prefix: "%(asctime)s.%(msecs)03d %(process)d TRACE %(name)s %(instance)s"
            heat_api:
              workers: 2
            heat_api_cfn:
              workers: 2
            cache:
              enabled: True
            oslo_messaging_notifications:
              driver: messagingv2
      test_results_stage_name: test_results
      zuul_copy_output:
        '{{ stage_dir }}/{{ test_results_stage_name }}.subunit': logs
        '{{ stage_dir }}/{{ test_results_stage_name }}.html': logs
        '{{ stage_dir }}/stackviz': logs
      extensions_to_txt:
        conf: true
        log: true
        yaml: true
        yml: true
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$

- project:
    check:
      jobs:
        - heat-templates-check
        # This is added to merge *.rst only changes
        - noop
    gate:
      jobs:
        - heat-templates-check
        - noop
