#!/bin/bash

set -uex

install-packages \
    policycoreutils \
    mcollective \
    httpd \
    openssh-server \
    rhc \
    ntpdate \
    rubygem-openshift-origin-node \
    openshift-origin-node-util \
    pam_openshift \
    openshift-origin-node-proxy \
    openshift-origin-port-proxy \
    openshift-origin-msg-node-mcollective \
    git \
    make \
    cronie \
    openshift-origin-cartridge-abstract \
    openshift-origin-cartridge-10gen-mms-agent-0.1 \
    openshift-origin-cartridge-cron-1.4 \
    openshift-origin-cartridge-diy-0.1 \
    openshift-origin-cartridge-haproxy-1.4 \
    openshift-origin-cartridge-mongodb-2.2 \
    openshift-origin-cartridge-mysql-5.1 \
    openshift-origin-cartridge-nodejs-0.6 \
    openshift-origin-cartridge-community-python-2.7 \
    openshift-origin-cartridge-community-python-3.3 \
    openshift-origin-cartridge-postgresql-9.2 \
    openshift-origin-cartridge-ruby-1.9 \
    openshift-origin-cartridge-php-5.4 \
    openshift-origin-cartridge-perl-5.16 \
    openshift-origin-cartridge-phpmyadmin-3.5 \
    puppet \
    system-config-firewall-base \
    autogen-libopts \
    ntp \
    libogg \
    libvorbis \
    flac \
    tzdata-java \
    wget \
    libasyncns \
    gsm \
    libsndfile \
    pulseaudio-libs \
    jline \
    rhino \
    ttmkfdir \
    xorg-x11-fonts-Type1 \
    1java-1.7.0-openjdk \
    openshift-origin-cartridge-jenkins-client-1.4 \
    jenkins \
    jenkins-plugin-openshift \
    openshift-origin-cartridge-jenkins-1.4

sed --in-place -e s/Type=oneshot/"Type=oneshot\nTimeoutSec=0"/ /lib/systemd/system/cloud-final.service

