#!/bin/bash

set -e

if [ -z ${DIB_RHSM_OSE_POOL:-} ]; then
	cat > /etc/yum.repos.d/openshift-node.repo <<YUM
[openshift_node]
name=OpenShift Node
baseurl=${DIB_CONF_REPO_BASE}/Node/x86_64/os/
enabled=1
gpgcheck=0
priority=1
sslverify=false

YUM

	cat > /etc/yum.repos.d/openshift-jboss.repo <<YUM
[openshift_jbosseap]
name=OpenShift JBossEAP
baseurl=${DIB_CONF_REPO_BASE}/JBoss_EAP6_Cartridge/x86_64/os/
enabled=1
gpgcheck=0
priority=1
sslverify=false

YUM

	cat <<YUM > /etc/yum.repos.d/jbosseap.repo
[jbosseap]
name=jbosseap
baseurl=${DIB_CONF_JBOSS_REPO_BASE}/jbeap/6/os
enabled=1
priority=3
gpgcheck=0

YUM

	cat <<YUM > /etc/yum.repos.d/jbossews.repo
[jbossews]
name=jbossews
baseurl=${DIB_CONF_JBOSS_REPO_BASE}/jbews/2/os
enabled=1
priority=3
gpgcheck=0

YUM
fi

install-packages \
yum-plugin-priorities \
rubygem-openshift-origin-node \
ruby193-rubygem-passenger-native \
openshift-origin-port-proxy \
openshift-origin-node-util \
policycoreutils-python \
openshift-origin-cartridge-cron \
openshift-origin-cartridge-diy \
openshift-origin-cartridge-haproxy \
openshift-origin-cartridge-jbossews \
openshift-origin-cartridge-jbosseap \
openshift-origin-cartridge-jenkins \
openshift-origin-cartridge-jenkins-client \
openshift-origin-cartridge-mysql \
openshift-origin-cartridge-perl \
openshift-origin-cartridge-php \
openshift-origin-cartridge-postgresql \
openshift-origin-cartridge-python \
openshift-origin-cartridge-ruby \
mcollective \
openshift-origin-msg-node-mcollective \
--skip-broken

# make sure not services were started that might hold on to mounts
service crond stop
