#!/bin/bash

set -uex

cat << EOF > /etc/yum.repos.d/puppetlabs-products.repo
[puppetlabs-products]
name=Puppet Labs Products Fedora 17 - x86_64
baseurl=http://yum.puppetlabs.com/fedora/f17/products/x86_64
gpgkey=http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
enabled=0
gpgcheck=1
EOF