#!/bin/bash

set -uex

cat > /etc/yum.repos.d/havana-epel.repo <<YUM
[havana-epel]
name=RHEL 6 Havana OpenStack
baseurl=http://repos.fedorapeople.org/repos/openstack/openstack-havana/epel-6/
enabled=1
gpgcheck=0
priority=2
sslverify=false

YUM

cat > /etc/yum.repos.d/cloudinit.repo <<YUM
[cloudinit]
name=Cloud Init Packages
baseurl=http://file.rdu.redhat.com/~calfonso/cloud-init/
failovermethod=priority
enabled=1
gpgcheck=0
YUM

install-packages cloud-init heat-cfntools

rm -f /etc/yum.repos.d/havana-epel.repo
rm -f /etc/yum.repos.d/cloudinit.repo
