#!/bin/bash

set -uex

cat > /etc/yum.repos.d/havana-epel.repo <<YUM
[havana-epel]
name=RHEL 6 Havana OpenStack
baseurl=http://repos.fedorapeople.org/repos/openstack/openstack-havana/epel-6/
enabled=1
gpgcheck=0
priority=2
sslverify=false

YUM
install-packages http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
install-packages cloud-init heat-cfntools

rm -f /etc/yum.repos.d/havana-epel.repo
rpm -e epel-release-6-8
